crm/urls.py
from django.conf.urls import url
from django.contrib import admin
from sales import views

urlpatterns = [
    # 增加学习记录
    url(r'^add_study_record/(\d+)', views.add_study_record, name='add_study_record'),
    # 学习记录
    url(r'^study_records/(\d+)', views.study_records, name='study_records'),

    # 编辑课程记录
    url(r'^edit_course_record/(\d+)', views.add_edit_course_record, name='edit_course_record'),
    # 添加课程记录
    url(r'^add_course_record/', views.add_edit_course_record, name='add_course_record'),
    # 课程记录
    url(r'^course_records/', views.course_records, name='course_records'),

    # 编辑报名记录
    url(r'^edit_enrollment/(\d+)', views.add_edit_enrollment, name='edit_enrollment'),
    # 添加报名记录
    url(r'^add_enrollment/', views.add_edit_enrollment, name='add_enrollment'),
    # 查看报名记录 一样的
    url(r'^enrollments/', views.enrollments, name='enrollments'),
    # 编辑跟进记录 和客户一样是同一个视图进行处理
    url(r'^edit_consult_record/(\d+)', views.add_edit_consult_record, name='edit_consult_record'),
    # 添加跟进记录
    url(r'^add_consult_record/', views.add_edit_consult_record, name='add_consult_record'),
    # 跟进记录展示
    url(r'^consult_record/', views.consult_record, name='consult_record'),
    # 我的客户 走的也是customer视图逻辑一样 就是url不同
    url(r'^my_customers/', views.customers, name='my_customers'),
    # 编辑客户 两个url同时匹配同一个视图函数进行处理
    url(r'^edit_customer/(\d+)', views.add_edit_customer, name='edit_customer'),
    #  添加客户
    url(r'^add_customer/', views.add_edit_customer, name='add_customer'),
    #  展示客户
    url(r'^customers/', views.customers, name='customers'),

    url(r'^login/$', views.login, name='login'),
    url(r'^$', views.login, name='login'),

    url(r'^register/$', views.register, name='register'),

    url(r'^admin/', admin.site.urls),
]

sales/models.py
from django.db import models
from multiselectfield import MultiSelectField

from django.utils.safestring import mark_safe
# Create your models here.
course_choices = (('LinuxL',  'Linux中高级'),
                  ('PythonFullStack', 'Python全栈高级'),)

class_type_choices = (('fulltime', '脱产班'),
                      ('online', '网络班'),
                      ('weekend', '周末班'),
                      )
source_type = (('qq', 'qq群'),
               ('referral', '内部转介绍'),
               ('website', '官方网站'),
               ('baidu_ads', '百度推广'),
               ('office_direct', '直接上门'),
               ('WoM', '口碑'),
               ('public class', '公开课'),
               )
enroll_status_choices = (
    ('signed', '已报名'),
    ('unsigned', '未报名'),
    ('studying', '学习中'),
    ('paid_in_full', '交全学费'),
)

score_choices = (
    (100, 'A+'),
    (90, 'A'),
    (85, 'B+'),
    (80, 'B'),
    (70, 'B-'),
    (60, 'C+'),
    (50, 'C'),
    (40, 'C-'),
    (0, 'D'),
    (-1, 'N/A'),
    (-100, 'COPY'),
    (-1000, 'FAIL'),
)

seek_status_choices = (
    ('A', '近期无报名计划'),
    ('B', '1个月内报名'),
    ('C', '2周内报名'),
    ('D', '1周内报名'),
    ('E', '定金'),
    ('F', '到班'),
    ('G', '全款'),
    ('H', '无效'),
)
# pay_type_choices = (
#     ('deposite', '订金/报名费'),
#     ('tuition', '学费'),
#     ('transfer', '转班'),
#     ('dropout', '退学'),
#     ('refund', '退款'),
# )
attendance_choices = (
    ('checked', '已签到'),
    ('vacate', '请假'),
    ('late', '迟到'),
    ('absence', '缺勤'),
    ('leave_early', '早退'),
)


class CourseRecord(models.Model):
    """
    课程记录表
    """
    day_num = models.IntegerField('节次', help_text='此处填写第几节课或者第几天课程...必须为数字')
    date = models.DateField(auto_now_add=True, verbose_name='上课时间')
    course_title = models.CharField('本节课程标题', max_length=64, blank=True, null=True)
    course_memo = models.TextField('本节课程内容', max_length=300, blank=True, null=True)
    has_homework = models.BooleanField(default=True, verbose_name='本节课有作业')
    homework_title = models.CharField('本节作业标题', max_length=64, blank=True, null=True)
    homework_memo = models.TextField('作业描述', max_length=500, blank=True, null=True)
    scoring_point = models.TextField('得分点', max_length=300, blank=True, null=True)
    re_class = models.ForeignKey('ClassList', verbose_name='班级')
    teacher = models.ForeignKey('UserInfo', verbose_name='讲师')

    class Meta:
        unique_together = ('re_class', 'day_num')
        verbose_name = '课程记录表'
        verbose_name_plural = '课程记录表'

    def __str__(self):
        return self.re_class.course + '第' + str(self.re_class.semester) + '期:第' + str(self.day_num) + '节课'


class StudyRecord(models.Model):
    """
    学习记录表
    """
    attendance = models.CharField('考勤', choices=attendance_choices, default='checked', max_length=64)
    score = models.IntegerField('本节成绩', choices=score_choices, default=1)
    homework_note = models.CharField(max_length=255, verbose_name='作业批语', blank=True, null=True)
    date = models.DateTimeField(auto_now_add=True)
    note = models.CharField('备注', max_length=255, blank=True, null=True)
    homework = models.FileField(verbose_name='作业文件', blank=True, null=True)
    course_record = models.ForeignKey('CourseRecord', verbose_name='某节课程')
    student = models.ForeignKey('Customer', verbose_name='学员')

    class Meta:
        unique_together = ('course_record', 'student')
        verbose_name = '学习记录表'
        verbose_name_plural = '学习记录表'

    def __str__(self):
        return self.student.name + ':' + self.course_record.re_class.campuses.name + self.course_record.re_class.course + ':' + str(self.course_record.re_class.semester) + ':' + str(self.course_record.day_num)


class Enrollment(models.Model):
    """
    报名表
    """
    why_us = models.TextField('为什么报名', max_length=1024, default=None, blank=True, null=True)
    your_expectation = models.TextField('学完想达到的具体期望', max_length=1024, blank=True, null=True)
    contract_approved = models.BooleanField('审批通过', help_text='在审阅完学员的资料无误后勾选此项，合同即生效', default=False)
    enrolled_date = models.DateTimeField(auto_now_add=True, verbose_name='报名日期')
    memo = models.CharField('备注', max_length=64, blank=True, null=True)
    delete_status = models.BooleanField('删除状态', default=False)
    customer = models.ForeignKey('Customer', verbose_name='客户名称')
    school = models.ForeignKey('Campuses')
    enrolment_class = models.ForeignKey('ClassList', verbose_name='所报班级')

    class Meta:
        unique_together = ('enrolment_class', 'customer')
        verbose_name = '报名表'
        verbose_name_plural = '报名表'

    def __str__(self):
        return self.customer.name + ':' + self.enrolment_class.get_course_display()


class ConsultRecord(models.Model):
    """
    跟进记录表
    """
    customer = models.ForeignKey('Customer', verbose_name='所咨询客户')
    note = models.TextField(verbose_name='跟进内容')
    status = models.CharField('跟进状态', max_length=8, choices=seek_status_choices, help_text='选择客户此时的状态')
    consultant = models.ForeignKey('UserInfo', verbose_name='跟进人', related_name='records')
    # 展示跟进记录的时候应该是按客户来划分的呀...就是说当前的客户是我的 然后我点击跟进记录 应该是能看到属于我的用户的所有跟进记录 就算是之前别的用户（如果他辞职了）跟进过的应该也能看见才对...
    # 所以展示跟进记录时本应该先根据当前用户的id查找出所有私户的id 然后根据私户的id查找出所有该客户的跟进记录
    # 但是我们规定好了当前用户只能查看自己的跟进记录 如果是其他用户对该客户的跟进记录 需要让他手动调给你看
    date = models.DateTimeField('跟进日期', auto_now_add=True)
    delete_status = models.BooleanField('删除状态', default=False)

    def __str__(self):
        return str(self.customer) + '  销售' + str(self.consultant)

    class Meta:
        verbose_name = '跟进记录表'
        verbose_name_plural = '跟进记录表'


class Department(models.Model):
    """
    部门表
    """
    name = models.CharField(max_length=12, verbose_name='部门名称')
    count = models.IntegerField(verbose_name='部门人数')  # 这个部门人数是假的 还没有根据用户统计

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '部门表'
        verbose_name_plural = '部门表'


class UserInfo(models.Model):
    """
    用户表：销售...
    """
    username = models.CharField(max_length=16)
    password = models.CharField(max_length=32)
    email = models.EmailField()
    telephone = models.CharField(max_length=16)
    is_active = models.BooleanField(default=True)
    depart = models.ForeignKey('Department', default=1)

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = '用户表'
        verbose_name_plural = '用户表'


class Customer(models.Model):
    """
    客户表：最开始的时候大家都是客户
    """
    qq = models.CharField(verbose_name='QQ', max_length=32, unique=True, help_text='QQ号必须唯一')
    qq_name = models.CharField('QQ昵称', max_length=32, blank=True, null=True)  # blank 和 null配合用 blank是校验时可以为空 null是存进数据库
    name = models.CharField('姓名', max_length=32, blank=True, null=True, help_text='学员报名后，请修改为真实姓名')
    sex_type = (('male', '男'), ('female', '女'))
    sex = models.CharField('性别', choices=sex_type, default='male', blank=True, null=True, max_length=16)
    birthday = models.DateField('出生日期', default=None, help_text='格式：yyyy-mm-dd', blank=True, null=True)
    phone = models.CharField('手机号', blank=True, null=True, max_length=12)
    source = models.CharField('客户来源', max_length=32, choices=source_type, default='qq')
    # self是本表 也可以直接写Customer 关联本表id字段（一对多关系）
    introduce_from = models.ForeignKey('self', verbose_name='转介绍自学员', blank=True, null=True, on_delete=models.CASCADE)

    # 多选Field原生的Form没有 需要手动安装 django-multiselectfield
    course = MultiSelectField('咨询课程', choices=course_choices)
    class_type = models.CharField('班级类型', max_length=64, choices=class_type_choices, default='fulltime')
    customer_note = models.TextField('客户备注', blank=True, null=True)
    status = models.CharField(
        '状态',
        choices=enroll_status_choices,
        max_length=64, default='unsigned',
        help_text='选择客户此时的状态',  # help_text 是针对admin应用里的
    )
    date = models.DateTimeField('咨询日期', auto_now_add=True)
    last_consult_date = models.DateField('最后跟进日期', auto_now_add=True)
    next_date = models.DateField('预计下次跟进日期', blank=True, null=True)
    consultant = models.ForeignKey('UserInfo', verbose_name='销售',
                                   related_name='customers', blank=True,  # 这个related_name是什么
                                   null=True, on_delete=models.CASCADE)
    class_list = models.ManyToManyField('ClassList', verbose_name='已报班级', blank=True)

    def __str__(self):
        return str(self.name) + ':'+self.qq

    class Meta:
        verbose_name = '客户表'
        verbose_name_plural = '客户表'

    @property
    def get_status_show(self):
        color_dict = {
              'signed': 'lightblue',
              'unsigned': 'red',
              'studying': 'lightgreen',
              'paid_in_full': 'lightgreen',
        }
        html = '<span style="background-color:{}">{}</span>'.format(color_dict[self.status],  self.get_status_display())
        return mark_safe(html)


class Campuses(models.Model):
    """
    校区表
    """
    name = models.CharField(verbose_name='校区', max_length=32)
    address = models.CharField(verbose_name='详细地址', max_length=124, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '校区表'
        verbose_name_plural = '校区表'


class ClassList(models.Model):
    """
    班级表
    """
    course = models.CharField('课程名称', max_length=64, choices=course_choices)
    semester = models.IntegerField('学期')
    campuses = models.ForeignKey('Campuses', verbose_name='校区', on_delete=models.CASCADE)
    price = models.IntegerField('学费', default=10000)
    memo = models.CharField('说明', blank=True, null=True, max_length=100)
    start_date = models.DateField('开班日期')
    graduate_date = models.DateField('结业日期', blank=True, null=True)
    teachers = models.ManyToManyField('UserInfo', verbose_name='老师')
    class_type = models.CharField(choices=class_type_choices, max_length=64, verbose_name='班额及类型', blank=True, null=True)

    class Meta:
        unique_together = ('course', 'semester', 'campuses')  # 定义联合唯一...
        verbose_name = '班级表'

sales/templates/add_consult_record.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
{% endblock %}


{% block content %}
{#        这个前端css样式真的吐了...页面本身css和bootstrap各种冲突...凑合用用 把功能实现了再说 #}
       <form class="form-horizontal" novalidate method="post">
       {% csrf_token %}
        {% for field in form_obj %}
                 <div class="form-group">
                <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{ field.label }}</label>
                <div class="col-sm-6">
                    {{ field }}
                </div>
                 <div class="col-sm-4">
                    <span style="color: red;">{{ field.errors }}</span>
                </div>
              </div>
        {% endfor %}



  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-primary">提交</button>
    </div>
  </div>
</form>





{% endblock %}

sales/templates/add_course_record.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
{% endblock %}


{% block content %}
{#        这个前端css样式真的吐了...页面本身css和bootstrap各种冲突...凑合用用 把功能实现了再说 #}
       <form class="form-horizontal" novalidate method="post">
       {% csrf_token %}
        {% for field in form_obj %}
                 <div class="form-group">
                <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{ field.label }}</label>
                <div class="col-sm-6">
                    {{ field }}
                </div>
                 <div class="col-sm-4">
                    <span style="color: red;">{{ field.errors }}</span>
                </div>
              </div>
        {% endfor %}



  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-primary">提交</button>
    </div>
  </div>
</form>





{% endblock %}

sales/templates/add_customer.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
{% endblock %}


{% block content %}
{#        这个前端css样式真的吐了...页面本身css和bootstrap各种冲突...凑合用用 把功能实现了再说 #}
       <form class="form-horizontal" novalidate method="post">
       {% csrf_token %}
        {% for field in form_obj %}
                 <div class="form-group">
                <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{ field.label }}</label>
                <div class="col-sm-6">
                    {{ field }}
                </div>
                 <div class="col-sm-4">
                    <span style="color: red;">{{ field.errors }}</span>
                </div>
              </div>
        {% endfor %}



  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-primary">提交</button>
    </div>
  </div>
</form>





{% endblock %}

sales/templates/add_enrollment.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
{% endblock %}


{% block content %}
{#        这个前端css样式真的吐了...页面本身css和bootstrap各种冲突...凑合用用 把功能实现了再说 #}
       <form class="form-horizontal" novalidate method="post">
       {% csrf_token %}
        {% for field in form_obj %}
                 <div class="form-group">
                <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{ field.label }}</label>
                <div class="col-sm-6">
                    {{ field }}
                </div>
                 <div class="col-sm-4">
                    <span style="color: red;">{{ field.errors }}</span>
                </div>
              </div>
        {% endfor %}



  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-primary">提交</button>
    </div>
  </div>
</form>





{% endblock %}

sales/templates/add_study_record.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
{% endblock %}


{% block content %}
{#        这个前端css样式真的吐了...页面本身css和bootstrap各种冲突...凑合用用 把功能实现了再说 #}
       <form class="form-horizontal" novalidate method="post">
       {% csrf_token %}
        {% for field in form_obj %}
                 <div class="form-group">
                <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{ field.label }}</label>
                <div class="col-sm-6">
                    {{ field }}
                </div>
                 <div class="col-sm-4">
                    <span style="color: red;">{{ field.errors }}</span>
                </div>
              </div>
        {% endfor %}



  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-primary">提交</button>
    </div>
  </div>

      <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <span style="color: red;">{{ form_obj.errors }}</span>
    </div>
  </div>
</form>





{% endblock %}

sales/templates/consult_record.html
{% extends 'base.html' %}

{% block content %}



    <form class="form-inline pull-right" style="margin-bottom: 10px" method="get">
    <select class="form-control" name="search_field" >
       <option value="">选择搜索字段</option>
        {% if search_field == 'name' %}
            <option value="qq">QQ</option>
             <option value="name" selected>客户名称</option>
            {% elif  search_field == 'qq'%}
             <option value="qq" selected>QQ</option>
             <option value="name">客户名称</option>
            {% else %}
              <option value="qq">QQ</option>
             <option value="name">客户名称</option>
        {% endif %}
</select>
        <span>&nbsp;</span>
  <div class="form-group">
    <input name='kw' class="form-control"  placeholder="输入搜索条件" value="{{ kw }}">
  </div>
  <button type="submit" class="btn btn-default">搜索</button>
</form>


     <form  action="" style="margin-bottom: 10px;" method="post">
     {% csrf_token %}
        <div class="form-inline pull-left">
            <select class="form-control" name="options" >
            <option>选择操作</option>
                <option value="delete_record" >删除跟进记录</option>
</select>&nbsp;
    <button class="btn btn-danger">GO</button>&nbsp;
     <a href="{% url 'add_consult_record' %}"><button type="button" class=" btn btn-primary">添加跟进记录</button></a>
        </div>


<table class="table table-striped  table-hover ">

    <tr class="active">
        <th><input type="checkbox" id="select_all"> 序号</th>
        <th>咨询客户</th>
        <th>QQ</th>
        <th>跟进内容</th>
        <th>跟进状态</th>
        <th>跟进人</th>
        <th>跟进日期</th>
        <th>操作</th>
    </tr>
    {% for consult_record_obj in consult_record_objs %}
        <tr class="active">
            <td><input type="checkbox" name="rids" value="{{ consult_record_obj.pk }}" > {{ forloop.counter }}</td>
            <td>{{ consult_record_obj.customer.name }}</td>
            <td>{{ consult_record_obj.customer.qq }}</td>
            <td>{{ consult_record_obj.note }}</td>
            <td>{{ consult_record_obj.get_status_display }}</td>
            <td>{{ consult_record_obj.consultant }}</td>
            <td>{{ consult_record_obj.date|date:'Y-m-d H:i:s'}}</td>
            <td><li class="fa fa-edit"><a href="{% url 'edit_consult_record' consult_record_obj.pk %}?next={{ request.get_full_path }}">编辑</a></li></td>
        </tr>
    {% endfor %}

</table>

    {{ pagination }}
          </form>
   {% comment %} <nav aria-label="Page navigation">
  <ul class="pagination">
    <li>
      <a href="/customers?page=1" aria-label="First">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    {% for foo in page_range %}
    <li><a href="/customers?page={{ foo }}">{{ foo }}</a></li>
    {% endfor %}
    
    <li>
      <a href="/customers?page={{ last }}" aria-label="Last">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
  </ul>
</nav>{% endcomment %}

{% endblock %}


{% block script %}
    <script>
        {#让checkbox反选#}
        $('#select_all').on('click',function () {
            for(i=0; i<$(':checkbox[name="rids"]').length; i++){
                if(jQuery($(':checkbox[name="rids"]')[i]).prop('checked')){
                    console.log('test');
                    jQuery($(':checkbox[name="rids"]')[i]).prop('checked', false);
                }else{
                    jQuery($(':checkbox[name="rids"]')[i]).prop('checked', true);
                }
            }
        })
    </script>
{% endblock %}

sales/templates/customers.html
{% extends 'base.html' %}

{% block content %}



    <form class="form-inline pull-right" style="margin-bottom: 10px" method="get">
    <select class="form-control" name="search_field" >
       <option value="">选择搜索字段</option>
        {% if search_field == 'qq' %}
             <option value="qq" selected>QQ</option>
             <option value="name">客户名称</option>
            {% elif search_field == 'name' %}
            <option value="qq" >QQ</option>
             <option value="name" selected>客户名称</option>
            {% else %}
             <option value="qq" >QQ</option>
             <option value="name">客户名称</option>
        {% endif %}
</select>
        <span>&nbsp;</span>
  <div class="form-group">
    <input name='kw' class="form-control"  placeholder="输入搜索条件" value="{{ kw }}">
  </div>
  <button type="submit" class="btn btn-default">搜索</button>
</form>


     <form  action="" style="margin-bottom: 10px;" method="post">
     {% csrf_token %}
        <div class="form-inline pull-left">
            <select class="form-control" name="options" >
            <option >选择操作</option>
                {% if content_title == '所有公户' %}
                    <option value="reverse_gs" >公户转私户</option>
                    {% else %}
                         <option value="reverse_sg">私户转公户</option>
                {% endif %}
</select>&nbsp;
    <button class="btn btn-danger">GO</button>&nbsp;
     <a href="{% url 'add_customer' %}"><button type="button" class=" btn btn-primary">添加客户</button></a>
        </div>


<table class="table table-striped  table-hover ">

    <tr class="active">
        <th><input type="checkbox" id="select_all"> 序号</th>
        <th>QQ</th>
        <th>客户名称</th>
        <th>性别</th>
        <th>报名状态</th>
        <th>销售</th>
        <th>跟进记录</th>
        <th>操作</th>
    </tr>
    {% for customer_obj in customers_obj %}
        <tr class="active">
            <td><input type="checkbox" name="cids" value="{{ customer_obj.pk }}" > {{ forloop.counter }}</td>
            <td>{{ customer_obj.qq }}</td>
            <td>{{ customer_obj.name }}</td>
            <td>{{ customer_obj.get_sex_display }}</td>
            <td>{{ customer_obj.get_status_show }}</td>
            <td>{{ customer_obj.consultant }}</td>
            <td><a href="{% url 'consult_record' %}?cid={{ customer_obj.pk }}">查看详情</a></td>
            <td><li class="fa fa-edit"><a href="{% url 'edit_customer' customer_obj.pk %}?next={{ request.get_full_path }}">编辑</a></li></td>
        </tr>
    {% endfor %}

</table>

    {{ pagination }}
          </form>
   {% comment %} <nav aria-label="Page navigation">
  <ul class="pagination">
    <li>
      <a href="/customers?page=1" aria-label="First">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    {% for foo in page_range %}
    <li><a href="/customers?page={{ foo }}">{{ foo }}</a></li>
    {% endfor %}
    
    <li>
      <a href="/customers?page={{ last }}" aria-label="Last">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
  </ul>
</nav>{% endcomment %}

{% endblock %}


{% block script %}
    <script>
        {#让checkbox反选#}
        $('#select_all').on('click',function () {
            for(i=0; i<$(':checkbox[name="cids"]').length; i++){
                if(jQuery($(':checkbox[name="cids"]')[i]).prop('checked')){
                    console.log('test');
                    jQuery($(':checkbox[name="cids"]')[i]).prop('checked', false);
                }else{
                    jQuery($(':checkbox[name="cids"]')[i]).prop('checked', true);
                }
            }
        })
    </script>
{% endblock %}

sales/templates/login.html
{% load static %}
<!DOCTYPE html>

<html lang="zh-CN">
<head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<title>登陆</title>
<link rel="stylesheet" href="{% static 'login/style.css' %}">
</head>

<body>
<div class="login-container">
<h1>欢迎登录</h1>
<div class="connect">
<p>Link the world. Share to world.</p>
</div>
<form action="{% url 'login' %}" method="post" id="loginForm">
    {% csrf_token %}
<div>
<input type="text" name="username" class="username" placeholder="用户名" autocomplete="off" value="admin">
</div>
<div>
<input type="password" name="password" class="password" placeholder="密码" oncontextmenu="return false" onpaste="return false">
</div>
    <span style="color: red;">{{ error_msg }}</span>
<button id="submit" type="submit">登 陆</button>
</form>
<a href="{% url 'register' %}">
<button type="button" class="register-tis">还有没有账号？</button>
</a>
</div>

<script src="{% static 'login/jquery.min.js' %}"></script>
<script src="{% static 'login/common.js' %}"></script>

<script src="{% static 'login/supersized.3.2.7.min.js' %}"></script>
<script src="{% static 'login/supersized-init.js' %}"></script>

<script src="{% static 'login/jquery.validate.min.js' %}"></script>


</body>

</html>